In [26]:
import pandas as pd
import numpy as np 

pthurl = '3rdpartyExport.csv'

df = pd.read_csv(pthurl)

print(df.shape)

df.head()

(955, 44)

,$/ sq ft,Sale Price,List Price,>90 Day Before Sale Zestimate,$ / sq ft for keywords,Close Date,Street Number,Street Name,Street Suffix,City,...,Avg,Count,Without,SqFt-Est Tot Fin,SqFt-Est Fin Lower Floor,SqFt-Est Fin Abv Grd,SqFt-Est Tot Bsmt,Year Built,Year Remodeled,Porch Type
0,$ 98,170000,178000,"$190,000",$210,04/16/2018,1013,GENESEE,Drive,Royal Oak,...,$200,154,$196,"1,726",700,"1,026",807,1952,NaN,"Patio, Porch"
1,$ 99,181000,179900,"$255,000",$155,08/22/2018,3266,HARVARD,Road,Royal Oak,...,$197,154,$196,"1,910",700,"1,210",800,1949,2015.0,Deck
2,$ 103,165500,199900,"$300,000",$200,12/03/2018,708,CAMPBELL,NaN,ROYAL OAK,...,$217,154,$196,"1,764",NaN,"1,764","1,128",1923,NaN,Porch - Enclosed
3,$ 105,290000,300000,"$430,000",$201,06/04/2018,2607,CARMAN,Avenue,Royal Oak,...,$232,154,$177,936,NaN,936,936,1953,NaN,Porch
4,$ 105,125000,159900,"$226,000",$206,04/23/2018,2931,ROCHESTER,Road,Royal Oak,...,$155,3,$196,"1,792",728,"1,064",728,1949,2017.0,"Deck, Porch"

In [29]:
def clean(dat: pd.DataFrame) -> pd.DataFrame: 
    def try_lower(x): 
        try: 
            return x.lower()
        except AttributeError:
            return x

    return (dat.assign(**{feat: dat[feat].apply(try_lower) for feat in dat.select_dtypes(exclude=[np.number]).columns})
            .rename(columns={' $/ sq ft ': 'price_per_sq_ft', 
                               '$ / sq ft for keywords': 'price_per_sq_ft_by_keyword', 
                               ' $/ sq ft .1': 'price_per_sq_ft_.1'})
            .rename(columns=lambda s: s.replace(' ', '_').lower())
            
           )

df = clean(pd.read_csv(pthurl))

df.columns

Index(['price_per_sq_ft', 'sale_price', 'list_price',
       '>90_day_before_sale_zestimate', 'price_per_sq_ft_by_keyword',
       'close_date', 'street_number', 'street_name', 'street_suffix', 'city',
       'county', 'zip5', 'unnamed:_12', 'beds_total', 'baths.lavs',
       'est_fin_abv_grd_sqft', 'acreage', 'architecture_level',
       'architecture_style', 'price_per_sq_ft_.1', 'basement_type',
       'unnamed:_21', 'sale_price.1', 'exterior', 'cooling',
       'exterior_features', 'garage_dimensions', 'garage_features',
       'garage_size', 'heating', 'original_list_price', 'photo_count',
       'pool_yn', 'public_remarks', 'avg', 'count', 'without',
       'sqft-est_tot_fin', 'sqft-est_fin_lower_floor', 'sqft-est_fin_abv_grd',
       'sqft-est_tot_bsmt', 'year_built', 'year_remodeled', 'porch_type'],
      dtype='object')

In [15]:
# transcribing from excel
row_to_keyword_mapper = {0: 'granite', 1: 'handyman', 2: 'new roof', 3: "ETC DON'T ACTULALY WANT TO TRANSCRIBE THIS"}

keywords = ['granite', 'handyman', 'new roof', ]

In [19]:
# Peyton says Doc2Vec from GenSim is what we want for this
# df.public_remarks